-- AlterTable
ALTER TABLE `tasks` ADD COLUMN `due_at` DATETIME(3) NULL,
    ADD COLUMN `priority` ENUM('NONE', 'LOW', 'MEDIUM', 'HIGH', 'URGENT') NOT NULL DEFAULT 'NONE',
    ADD COLUMN `status` ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CLOSED') NOT NULL DEFAULT 'TODO';
